import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/home/Navbar/responsiveNav";

const font = Oswald({
    weight :['300','500','600',],
    subsets:['latin'],
})

export const metadata: Metadata = {
  title: "Orolya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}>
         <ResponsiveNav />
      {children}
      </body>
    </html>
  );
}
